### ISSUE TITLE
Is it really argon dashboard pro or just argon dashboard

### ISSUE THREAD

**Issue by ziming** [creativetimofficial/ct-argon-dashboard-pro-laravel#1]
I went to https://github.com/laravel-frontend-presets/argon and it's the normal argon dashboard. Not the pro version as mentioned in the Readme

I'm happy enough with argon dashboard but if it is really the pro version for free that will be great

**Comment by Ghitu** [comment]
Hi @ziming,
Thank you for your interest. The pro version is now available for purchase here https://www.creative-tim.com/product/argon-dashboard-pro-laravel

Regards
Alin
