### ISSUE TITLE
Sweet Alert:  Confirm popup not appear

### ISSUE THREAD

**Issue by hangtuah** [creativetimofficial/ct-argon-dashboard-pro-laravel#12]
I'm using sweet alert button, but change to <a href..>
If I set the link to ( <a href="#" ... >, the confirm popup is work.

The problem is if i change to route ( <a href="{{ route('xxx') }}" ....>, the confirm popup not appear although the background action process still work.  

Please help. Thanks

**Comment by rarestoma** [comment]
Hi @hangtuah,

Thank you for working with our products.

Can you please give me a photo of the code so I can see clearly what happens? Also, I found this tutorial(https://medium.com/@hossain.naime/how-to-implement-sweet-alert-in-laravel-application-7cfe0fe4dd57).

I hope it helps.

All the best,
Rares
