### ISSUE TITLE
Laravel 6 translation

### ISSUE THREAD

**Issue by tomandersen** [creativetimofficial/ct-argon-dashboard-pro-laravel#13]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

{{ __('Validation') }} and {{ __('validation') }} will return the string 'Validation' - in validation.blade.php line 10

# Current Behavior

The translation system sees the word 'validation' and loads the entire file validation.php from the en lang resources, which is not right.

# Failure Information (for bugs)

ErrorException (E_ERROR)
htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/tandersen/code/aotc-app/resources/views/pages/validation.blade.php)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

install argon
composer install
Laravel 6
Visit 'Validation' from the left side bar
Crashes

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Context
macOS 10.14.6
Chrome

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by tomandersen** [comment]
Expected Behavior
{{ __('Validation') }} and {{ __('validation') }} will return the string 'Validation' - in validation.blade.php line 10 

Current Behavior
The translation system sees the word 'validation' and loads the entire file validation.php from the en lang resources, which is not right.

Failure Information (for bugs)
ErrorException (E_ERROR)
htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/tandersen/code/aotc-app/resources/views/pages/validation.blade.php)
Previous exceptions


Steps to Reproduce
Please provide detailed steps for reproducing the issue.

install argon 
composer install
Laravel 6
Visit 'Validation' from the left side bar 
Crashes


Context
macOS 10.14.6
Chrome


NOTES:
Changing the string to anything other than 'validation' works. 

I think that the project should switch to using en.json instead of old php translation files. 


![Screen Shot 2019-12-02 at 9 48 22 AM](https://user-images.githubusercontent.com/221405/69968672-e7ac0500-14e8-11ea-9c78-0b7df0babcca.png)

**Comment by tomandersen** [comment]
IF you can't reproduce, please change line 10 in validation.blade.php to __('validation') with lower case to see the issue.

**Comment by tomandersen** [comment]
the project should switch to using en.json instead of old php translation files.

**Comment by teamupdivision** [comment]
Hello @tomandersen. Thank you for using our products.
We've made the necessary fixes, please check them out by downloading the archive again from your downloads section.

Best
Eugen
