### ISSUE TITLE
Sidebar animation bug [Premium Support]

### ISSUE THREAD

**Issue by timotheeduran** [creativetimofficial/ct-argon-dashboard-pro-laravel#15]
Hi,

I'm using Argon Pro for Laravel with the sidebar menu like on your demo. The thing is that on a big screen, big enough for the sidebar to be expanded, there is a weird animation when changing pages. The sidebar makes a kind of "slide-in" from the left and the content is progressively resized. The expected behavior would be that the sidebar stays fixed across different pages.

![ezgif-2-b0f7b6094ca2](https://user-images.githubusercontent.com/26303997/70389862-6d3a2400-19c5-11ea-96c3-636cb87c909d.gif)

It happens with both Chrome and Safari on macOS. (Maybe other navigators but I haven't tried). You can try it on your demo, it also makes this weird animation. How can I remove this animation? 

Thank you very much and have a nice day!

**Comment by rarestoma** [comment]
Hi @burgercode,

Thank you for working with our products.

Please remove the transition from the .sidenav class, it should work fine now.

All the best,
Rares

**Comment by timotheeduran** [comment]
Hi,

Thank you for your answer. The bug is resolved with this quick fix bug there is no animation anymore when hovering the minimized menu. -> It becomes bigger without animation but before it had a nice animation.

Do you have a fix that removes the buggy animation while changing pages but keeps the animation when changing the sidebar width?

No animation - with quickfix provided:
![ezgif-4-5017a76106a4](https://user-images.githubusercontent.com/26303997/70460288-3db71480-1ab6-11ea-9742-4f91ffa97314.gif)

Animation - before quickfix but with bug while changing pages
![ezgif-4-ef4d54dbcdc9](https://user-images.githubusercontent.com/26303997/70460309-4871a980-1ab6-11ea-9c11-a7722746bea3.gif)

**Comment by timotheeduran** [comment]
Hi, do you have any ideas on how to solve this?

**Comment by rarestoma** [comment]
Hi @burgercode,

Sorry for my late response. I checked and please try adding 'g-sidenav-show g-sidenav-pinned' classes on each body tag you are using. This will let the sidebar always open and that transition will not be visible when you switch pages. Also, please add back the .sidenav transition.

Please let me know if it works.

All the best,
Rares
