### ISSUE TITLE
Sketch File - Argon Dashboard Laravel Pro

### ISSUE THREAD

**Issue by jamesnextdoor** [creativetimofficial/ct-argon-dashboard-pro-laravel#16]
Hello,

We'd like to inquire regarding the inclusion of the sketch file on Argon Dashboard Laravel Pro latest version. Will you be able to share a preview of what's inside the file? Are we expecting that there are page templates already?

Our team is aiming to avail today. So, your response would be much appreciated.

My email is aaron.chavez@dottystylecreative.com.

Regards,

**Comment by jamesnextdoor** [comment]
We've tried downloading this one: https://github.com/Epikly/Argon-Design-System-Sketch
but we can't see the widgets, tables for the Admin Panel.

**Comment by teamupdivision** [comment]
issue was resolved outside github
