### ISSUE TITLE
Is it possible to add react UI in argon-dashboard-pro-laravel

### ISSUE THREAD

**Issue by raliqala** [creativetimofficial/ct-argon-dashboard-pro-laravel#17]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by raliqala** [comment]
i have node modules installed
everything is working so i wanted to use react on this one page then
i tried to add react ui by running **php artisan ui react** and i got this error


```
   ErrorException

  copy(C:\xampp\htdocs\All projects\latest one\travSIM_Admin_Panel\resources\sas
s/_variables.scss): failed to open stream: No such file or directory

  at C:\xampp\htdocs\All projects\latest one\travSIM_Admin_Panel\vendor\laravel\
ui\src\Presets\Bootstrap.php:42
    38|      * @return void
    39|      */
    40|     protected static function updateSass()
    41|     {
  > 42|         copy(__DIR__.'/bootstrap-stubs/_variables.scss', resource_path('
sass/_variables.scss'));
    43|         copy(__DIR__.'/bootstrap-stubs/app.scss', resource_path('sass/ap
p.scss'));
    44|     }
    45|
    46|     /**

  1   C:\xampp\htdocs\All projects\latest one\travSIM_Admin_Panel\vendor\laravel
\ui\src\Presets\Bootstrap.php:42
      copy("C:\xampp\htdocs\All projects\latest one\travSIM_Admin_Panel\vendor\l
aravel\ui\src\Presets/bootstrap-stubs/_variables.scss", "C:\xampp\htdocs\All pro
jects\latest one\travSIM_Admin_Panel\resources\sass/_variables.scss")

  2   C:\xampp\htdocs\All projects\latest one\travSIM_Admin_Panel\vendor\laravel
\ui\src\Presets\Bootstrap.php:15
      Laravel\Ui\Presets\Bootstrap::updateSass()
```

**Comment by teamupdivision** [comment]
Hello, thank you for using our products.

Laravel Argon Dasboard PRO was not meant to be used with React UI on top of it.
Unfortunately, we cannot offer support for code done outside the product scope.

All the best
