### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by demon0430** [creativetimofficial/ct-argon-dashboard-pro-laravel#18]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

**I expect text-break to wrap the text inside the td when the class is defined**

# Current Behavior

**the text inside the td is not wrapping as expected**

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hello and thank you for using Creative Tim products.

I'm not sure what table or what page you are referring to. Is it the items page that it's not wrapping text on more than one row?
It is intended that way so that the table has consistent row size in order to view quickly all the information.

If you still want to wrap text you can replace this css code:
`.table td, .table th {
    font-size: .8125rem;
    white-space: nowrap;
}`

with 

`.table td, .table th {
    font-size: .8125rem;
    white-space: normal;
}`

All the best

**Comment by demon0430** [comment]
appreciate the response. the suggestion works on my end. My goal was to wrap the text inside the td to avoid/minimize scrolling on mobile when the width of the table exceeds the viewport size.

thanks

**Comment by teamupdivision** [comment]
glad we could be of help

**Comment by demon0430** [comment]
Hi,

I was able to follow the instruction provided, initially the provided solution works , but checking it on a samsung galaxy tab A , the test is not wrapping as expected. Is there anything i miss with this solution ?
