### ISSUE TITLE
Validation Dropdown Issue

### ISSUE THREAD

**Issue by mmuhamadamirzaidi** [creativetimofficial/ct-argon-dashboard-pro-laravel#19]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ /] I am running the latest version
- [/ ] I checked the documentation and found no answer
- [/ ] I checked to make sure that this issue has not already been filed
- [ /] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Should highlight the dropdown border for valid/invalid just like the other input.

[Screenshot how it should work](https://drive.google.com/file/d/1yanWUHxIR8AmKRQExcrIAJxOjpCqICdU/view?usp=sharing)

![Validation-Should-Be](https://user-images.githubusercontent.com/44740963/90950333-f07fa500-e482-11ea-82dd-2d71df7b9a75.PNG)

# Current Behavior

The validation feedback is working, but it doesn't highlight the dropdown border for valid/invalid. It used the primary color as we select the selection.

[Dropdown Select](https://drive.google.com/file/d/1_I6wPnAPfamiMa1KiKHjwlzrOMkiwQ4s/view?usp=sharing)

![Dropdown](https://user-images.githubusercontent.com/44740963/90950391-769beb80-e483-11ea-9d0c-ac02caa78ab6.PNG)

[Screenshot invalid](https://drive.google.com/file/d/15nMMsBbkJXZtkGv--9r3SssMNibarlLi/view?usp=sharing)

![Error-Feedback](https://user-images.githubusercontent.com/44740963/90950332-f07fa500-e482-11ea-93e0-b1a6225a2462.PNG)

[Screenshot valid](https://drive.google.com/file/d/1qwoX8wwThB-ivHeacqGKHHoOPF9XzJPK/view?usp=sharing)

![Correct-Feedback](https://user-images.githubusercontent.com/44740963/90950330-ef4e7800-e482-11ea-9227-774e319407e8.PNG)

Code Snippet

`<div class="form-group">`
`    <label class="form-control-label" for="user-schedule">Work Schedule</label>`
`    <select class="form-control" data-toggle="select" id="user-schedule" required>`
`        <option value="">Select Work Schedule</option>`
`        <option value="1">Schedule 1</option>`
`        <option value="2">Schedule 2</option>`
`    </select>`
`    <div class="valid-feedback">`
`        Looks good!`
`    </div>`
`    <div class="invalid-feedback">`
`        Please select the work schedule!`
`    </div>`
`</div>`

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click the submit button for submitting the form.
2. All input validation was good, except for the dropdown selection.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Computer
* Operating System: Windows
* Browser and Version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by rarestoma** [comment]
Hi @mmuhamadamirzaidi,

Thank you for working with our products.

Can you please give show us how did you implement the javascript of the validation so I can test it closely? It should add `'is-valid' / 'is-invalid'` classes to the input so the border will turn to green(success)/red(error).

Thank you,
Rares

**Comment by mmuhamadamirzaidi** [comment]
Hi @rarestoma,

Thanks for your reply.

I used the `needs-validation` class in the form tag, and also `valid-feedback`/ `invalid-feedback` class in the feedback. All the input type like text input, number, file, and normal dropdown are working fine, unless for search dropdown.

Sample form code I used:

![form-code](https://user-images.githubusercontent.com/44740963/91059635-8d496a80-e65c-11ea-9a39-fe94fad7eb2e.PNG)

Sample code for text input:

![text-input](https://user-images.githubusercontent.com/44740963/91058453-0ba50d00-e65b-11ea-8a75-9a8f04a07386.PNG)

Output after validate:

![text-input-output](https://user-images.githubusercontent.com/44740963/91058535-27a8ae80-e65b-11ea-9245-1a5cafa0c85a.PNG)

Sample code for file input:

![file-input](https://user-images.githubusercontent.com/44740963/91058681-57f04d00-e65b-11ea-9861-156a9e4e94db.PNG)

Output after validate:

![file-input-output](https://user-images.githubusercontent.com/44740963/91058775-748c8500-e65b-11ea-8a26-905c27171f20.PNG)

Normal dropdown:

![normal-dropdown-invalid](https://user-images.githubusercontent.com/44740963/91058925-a69de700-e65b-11ea-8543-684cedbcf857.PNG)

![normal-dropdown-valid](https://user-images.githubusercontent.com/44740963/91058935-aa316e00-e65b-11ea-9def-ca3d0e7c58b8.PNG)

Sample code for search dropdown with ` data-toggle="select"`:`

![search-dropdown](https://user-images.githubusercontent.com/44740963/91059192-fb416200-e65b-11ea-9685-77d0994a8d9b.PNG)

Output after validate:

When select search dropdown:

![search-dropdown-when-select](https://user-images.githubusercontent.com/44740963/91059833-c97ccb00-e65c-11ea-8555-b1482b4e694e.PNG)


Valid:

![search-dropdown-valid](https://user-images.githubusercontent.com/44740963/91059358-2fb51e00-e65c-11ea-9907-4b00d136f8c3.PNG)

Even after select, it takes the primary color as border color, not the green.

Invalid:

![search-dropdown-invalid](https://user-images.githubusercontent.com/44740963/91059380-380d5900-e65c-11ea-8a37-105076ec758c.PNG)

For invalid, it doesn't put red color. The `valid-feedback`/ `invalid-feedback` feedback is working fine.

Please help me to solve this. Thanks in advance.

**Comment by rarestoma** [comment]
Hi @mmuhamadamirzaidi,

Thank you for providing me all the details.

Can you please add these lines on the CSS and try again?

```
.was-validated .form-control:valid  ~ .select2 .select2-selection{
  border: 1px solid #2dce89;
}

.was-validated .form-control:invalid  ~ .select2 .select2-selection{
  border: 1px solid #fb6340;
}
```

I tested it and now the border of the selects turns to green/red when is valid/invalid.

Please let me know if it works.

Thank you,
Rares

**Comment by mmuhamadamirzaidi-work** [comment]
Hi @rarestoma,

Thanks for your time and respond to help me out to solve the validation search dropdown issue. And yeah, your solution works like charms!

I appreciate your kindness and support. Once again, thanks!

Sincerely, 
Muhamad Amir

**Comment by mmuhamadamirzaidi** [comment]
Hi @rarestoma,

Thanks for your time and respond to help me out to solve the validation search dropdown issue. And yeah, your solution works like charms!

I appreciate your kindness and support. Once again, thanks!

Sincerely, 
Muhamad Amir
