### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by jhonnymakis** [creativetimofficial/ct-argon-dashboard-pro-laravel#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version
- [YES ] I checked the documentation and found no answer
- [YES ] I checked to make sure that this issue has not already been filed
- [YES ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

ErrorException (E_ERROR)
htmlspecialchars() expects parameter 1 to be string, array given (View: C:\Projetos\2019\argon-dashboard-pro-laravel-master\resources\views\layouts\navbars\sidebar.blade.php) (View: C:\Projetos\2019\argon-dashboard-pro-laravel-master\resources\views\layouts\navbars\sidebar.blade.php) (View: C:\Projetos\2019\argon-dashboard-pro-laravel-master\resources\views\layouts\navbars\sidebar.blade.php)
Previous exceptions
htmlspecialchars() expects parameter 1 to be string, array given (View: C:\Projetos\2019\argon-dashboard-pro-laravel-master\resources\views\layouts\navbars\sidebar.blade.php) (View: C:\Projetos\2019\argon-dashboard-pro-laravel-master\resources\views\layouts\navbars\sidebar.blade.php) (0)
htmlspecialchars() expects parameter 1 to be string, array given (View: C:\Projetos\2019\argon-dashboard-pro-laravel-master\resources\views\layouts\navbars\sidebar.blade.php) (0)
htmlspecialchars() expects parameter 1 to be string, array given (0)

# Current Behavior

# Failure Information (for bugs)

## Steps to Reproduce

- Follow the README.md
- Run "php artisan serve" 
- Login into dashboard 

After this a saw the issue.

## Context

PHP Version 7.3.1
php artisan serve

**Comment by heyharii** [comment]
@jhonnymakis have you solved this issue ?

**Comment by jhonnymakis** [comment]
Sidebar / grid / validation / 

sidebar.blade.php has a li.nav-item {{ __('Validation') }} this is a reserved word, I changed to {{ __('Validations') }} and it worked

Line 138

**Comment by Ghitu** [comment]
Hello guys, thank you for the feedback and help!
The issues is fixed in the new Argon Laravel PRO version which just got published.

Please download it and send us your feedback. We also added more features to it. We wrote a blog post about the update: https://updivision.com/blog/post/introducing-a-new-version-of-argon-dashboard-pro-laravel

Thank you!
