### ISSUE TITLE
Text Not Wrapping on mobile / tablet

### ISSUE THREAD

**Issue by demon0430** [creativetimofficial/ct-argon-dashboard-pro-laravel#21]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I opened this ticket before https://github.com/creativetimofficial/ct-argon-dashboard-pro-laravel/issues/18 and was provided a solution to the problem. Expectation was text should wrap on mobile.

# Current Behavior

Currently Text is not wrapping on mobile / tablet (galaxy tab a).  I have a table that has data populated from the DB and pagination and filtering handled by data table.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Galaxt Tab A
* Operating System:
* Browser and Version: Chrome - latest version

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi, 

I can not reproduce the bug, but please try to add overflow-wrap: normal after white-space: normal; property

Thanks

**Comment by demon0430** [comment]
Hi,

Apologies if you can not reproduce the issue but appreciate the reply. I would try your suggestion and will let you know if that resolve my issue.

Thanks

**Comment by demon0430** [comment]
Hi,

I think my issue is fixed. Appreciate the assistance.

Thanks

**Comment by vladimir-panfilov** [comment]
Hi,

Glad that you solved the issue. I will close this ticket.
If you have any other questions do not hesitate to contact us!

Best
