### ISSUE TITLE
File not found resources/sass/app.scss

### ISSUE THREAD

**Issue by fszostak** [creativetimofficial/ct-argon-dashboard-pro-laravel#23]
File not found ./resources/sass/app.scss

## Failure Logs

ERROR in multi ./resources/js/app.js ./resources/sass/app.scss
Module not found: Error: Can't resolve '/Users/fszostak/Downloads/argon-dashboard-pro-laravel-master/resources/sass/app.scss' i

**Comment by teamupdivision** [comment]
Hi @fszostak,

Thank you for using Creative-Tim products!
Unfortunately, we are not using sass for this theme now, but we will implement it in the near future.

Best,

UPDIVISION

**Comment by fszostak** [comment]
How do I render assets?

I ran the command:

$ npm run dev

**Comment by teamupdivision** [comment]
Hi @fszostak,

You cannot render scss assets.
We will work in the future on a version where you can do.

Best,

UPDIVISION

**Comment by fszostak** [comment]
Solved!

I had put the vendor folder on .gitignore

Thanks!

**Comment by rhyudek1** [comment]
Hello,

Is there an estimated date for the assets? I bought the template and it is the only thing that is holding me back.
I ask to know if it is faster for me to make myself the changes in my project, or I wait for your update

Regards.

**Comment by teamupdivision** [comment]
HI @rhyudek1,

We plan on doing the update in the next couple of weeks. 
Wil keep you posted about it.

Best,

UPDIVISION

**Comment by rhyudek1** [comment]
Hi, is there any news?

**Comment by teamupdivision** [comment]
Hello @rhyudek1,
Thank you for waiting. We've made the update.
You can now download the updated version of the project.

Thank you

**Comment by teamupdivision** [comment]
@fszostak please check it out, you can now render assets. We've made the update.
You can now download the updated version of the project.

**Comment by rhyudek1** [comment]
@teamupdivision Hi there,

I tried to download it again to see the changes from https://www.creative-tim.com/downloads but the file is not up to date

**Comment by teamupdivision** [comment]
Hi, can you please let me know what is the archive filename you downloaded?

**Comment by rhyudek1** [comment]
@teamupdivision 

Bundles - 1 Package
Argon Dashboard Pro Laravel (Freelancer licence)
Laravel Button
![Screenshot_20201221_152324](https://user-images.githubusercontent.com/647189/102809276-79124180-43a0-11eb-8e45-d838616a9495.png)

**Comment by teamupdivision** [comment]
Hello, 
Just to make sure, are you looking in the right folder, the scss is in
`argon-dashboard-pro-laravel-demo\resources\assets\scss`

Thank you
