### ISSUE TITLE
How to display existing files on server in Dropzone js on Laravel Project?

### ISSUE THREAD

**Issue by BlueStarSystem** [creativetimofficial/ct-argon-dashboard-pro-laravel#25]
### Version
1.2.3
### Operating System
Windows
### Device
PC
### Browser & Version
Firefox 83
### Steps to reproduce
I'd like to see an example. Is there anyone who can help me?
### What is expected?
Preview image stored in the server.
### What is actually happening?
Nothing

---

**Comment by teamupdivision** [comment]
Hello, 
What do you want exactly?
Can you please give us  more details?

**Comment by BlueStarSystem** [comment]
I used Dropzone as per your instuctions and samples. Now, I'd like to see an example on how to display existing files on server in Dropzone working in a Laravel Project.
I.e. I saved an image on a server. I open an edit form. In the edit form I need to see the image previously saved in the server.

**Comment by teamupdivision** [comment]
There is no Dropzone implementation in the Laravel examples.
There is only the Dropzone example with HTML, CSS and JS.

Unfortunately we cannot help you with something that is not part of the product
