### ISSUE TITLE
auth/verify is trying to load sidebar

### ISSUE THREAD

**Issue by booknookcanby** [creativetimofficial/ct-argon-dashboard-pro-laravel#26]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

If user email not verified, show auth/verify (auth.verify.blade.php)

# Current Behavior

getting error about loading sidebar which should not be loading from the verify view

# Failure Information (for bugs)

ErrorException
Undefined variable: parentSection (View: C:\projects\hitek_erp\resources\views\layouts\navbars\sidebar.blade.php)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1. add  implements MustVerifyEmail to user class
2. add this route to project

Route::get('/email/verify', function () {
    return view('auth.verify');
})->middleware('auth')->name('verification.notice');

3. register user

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: desktop
* Operating System: windows 10
* Browser and Version: chrome Version 87.0.4280.88 (Official Build) (64-bit)
![Capture](https://user-images.githubusercontent.com/74828717/103461540-f0ff3680-4cd3-11eb-808b-ef1c08282669.PNG)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hello, @booknookcanby 
Thanks for using our products.
We'll follow up soonest with a response.
Thank you

**Comment by teamupdivision** [comment]
Hello, 
We have fixed the issue and pushed it to the project archive you can download from the Creative Tim website.
If you find anymore issues please reopen the ticket.

All the best.
