### ISSUE TITLE
User cannot change his password in profile's settings

### ISSUE THREAD

**Issue by sztanga** [creativetimofficial/ct-argon-dashboard-pro-laravel#27]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When I change my password in the profile I want the password to be changed

# Current Behavior

Some users have reported that they have an error when trying to update their password (they probably use autofill but it shouldn't matter)

# Failure Information (for bugs)

I couldn't replicate this issue 

## Steps to Reproduce

Couldn't replicate it, some of the users have send me a video where they enter current password, new password and repeating new password, then they got an error from here (profile controller):

```
if (Gate::denies('update', auth()->user())) {
    return back()->withErrors([
        'not_allow_password' => __('You are not allowed to change the password for a default user.')
    ]);
}
```

## Context

Didn't change anything with regards to user profile. I use latest version of argon pro on ubuntu 20.04 with LAMP stack, php 7.4, mysql 8

## Failure Logs

None

**Comment by teamupdivision** [comment]
Hello @sztanga!
Thanks for using our products.
Can you please let me know what is the value of IS_DEMO in your .env file. 

Thank you

**Comment by sztanga** [comment]
Thanks for your response!

`IS_DEMO=false`

The bug was fixed when I removed this part of the code from ProfileController but I think its not a solution:
```
if (Gate::denies('update', auth()->user())) {
    return back()->withErrors([
        'not_allow_password' => __('You are not allowed to change the password for a default user.')
    ]);
}
```

**Comment by teamupdivision** [comment]
Hello,

We have fixed the issue and pushed it to the project.
You can download the archive from the downloads section in the Creative Tim website.

All the best

**Comment by sztanga** [comment]
Great stuff, thanks for quick response!
