### ISSUE TITLE
Page flickers on every load

### ISSUE THREAD

**Issue by wilcooudijk** [creativetimofficial/ct-argon-dashboard-pro-laravel#28]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed
- [Yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

With the sidebar nav expanded, when I click a link, I expect the page to load nicely.

# Current Behavior

With the sidebar nav expanded, when I click a link, the page flickers when it loads. The navbar seems to start in a collapsed state, before expanding. The page does not build well as a result.

I am working in the latest version of Chrome on a Mac.

**Comment by teamupdivision** [comment]
Hello @wilcooudijk 
Thanks for using Creative Tim products and sorry to hear you're experiencing issues with the Argon theme.
Can you please send me a short video screen capture to see exactly how the theme behaves?

Thank you

**Comment by wilcooudijk** [comment]
Hi there,

Here’s a link to the video: <removed>

Thanks,
Wilco


On Feb 1, 2021, at 9:45 PM, Updivision Team <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello @wilcooudijk<https://github.com/wilcooudijk>
Thanks for using Creative Tim products and sorry to hear you're experiencing issues with the Argon theme.
Can you please send me a short video screen capture to see exactly how the theme behaves?

Thank you

**Comment by teamupdivision** [comment]
Hello, thanks for following up
We made the update to fix the issue.
You can download the product archive from the downloads section on Creative Tim

All the best

**Comment by wilcooudijk** [comment]
Thanks for the prompt support. It works like a charm now.


On Feb 2, 2021, at 8:55 AM, Updivision Team <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello, thanks for following up
We made the update to fix the issue.
You can download the product archive from the downloads section on Creative Tim

All the best

**Comment by teamupdivision** [comment]
Thank you!

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Comment by wesleyfraser** [comment]
Hi,
How do we see what was updated in the new version to fix the flicker issue? I have an existing site with the argon dashboard pro and I'm also experiencing the flickering issue?

**Comment by teamupdivision** [comment]
Hi @wesleyfraser,

Thank you for using Creative Tim products and for checking on this. We updated the following items:

public/argon/js/argon.js 
public/css/argon.css 
resources/views/layouts/app.blade.php

Please let us know if this helped and if there is any other issue. 

Best, 
UPDIVISION Team
