### ISSUE TITLE
The Argon Datatables is not Responsive like Material Datatables [Premium Support]

### ISSUE THREAD

**Issue by niellevince** [creativetimofficial/ct-argon-dashboard-pro-laravel#29]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [/] I am running the latest version
- [/] I checked the documentation and found no answer
- [/] I checked to make sure that this issue has not already been filed
- [/] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
In material datatables, the columns is hidden when responsive and there is an expand button at the first column. 
![image](https://user-images.githubusercontent.com/73742027/107747726-ddbf9c00-6d52-11eb-801a-a26010f860f7.png)

# Current Behavior

The Argon Design does not take this behaviour, it needs more scrolling in mobile which is not good especially when users can see the clipped version of the table. Sometimes its confusing and especially in desktop version. You have to scroll horizontally to reach the end.
![image](https://user-images.githubusercontent.com/73742027/107747533-84576d00-6d52-11eb-8799-864fafba2a08.png)

The argon

**Comment by teamupdivision** [comment]
Hi @niellevince,

Thanks for using Creative Tim products.

This is the default behaviour of the Argon Pro Laravel Dashboard. We cannot help you with a feature that is present on a different dashboard product. 

Thank you.
