### ISSUE TITLE
Error After Installations 

### ISSUE THREAD

**Issue by heyharii** [creativetimofficial/ct-argon-dashboard-pro-laravel#3]
Hello, need help, I got this error when try to login, laravel v 5.7, PHP 7.1.23

![Screen Shot 2019-03-22 at 09 01 12](https://user-images.githubusercontent.com/14860018/54796183-cf10fd00-4c81-11e9-95e3-98043bdba0c6.png)

**Comment by Ghitu** [comment]
Hello & thank you for your feedback! 
This is fixed in the new Argon Laravel PRO version which just got published. 
Please download it and send us your feedback.
https://www.creative-tim.com/product/argon-dashboard-pro-laravel
Thank you
