### ISSUE TITLE
No validation for image upload on user profile

### ISSUE THREAD

**Issue by sztanga** [creativetimofficial/ct-argon-dashboard-pro-laravel#30]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Image should be validated before uploading it to User Profile

# Current Behavior

Currently there's no validation on file upload which leads to file injection vuln which is a huge security hole

**Comment by teamupdivision** [comment]
Hi @sztanga,

Thanks for reporting this issue. 

Could you please send a few more details to us on the issue you are facing and exactly the type of validation that is not working properly? This is already using validation for image uploads, so we want to make sure we understand the issue correctly.

Thank you.

**Comment by teamupdivision** [comment]
Hi @sztanga,

We would like to check if you still have any issues with the validation. 

We've pushed a fix to this problem.
You can either download again the product from the downloads section in the Creative Tim website or check the latest commit we did in this Github repository.

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @sztanga,

Hope this solved the problem. I will go ahead and close this ticket.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
