### ISSUE TITLE
Truly Laravel 8 with Breeze and / or  Jetstream 

### ISSUE THREAD

**Issue by alinmiron** [creativetimofficial/ct-argon-dashboard-pro-laravel#31]
We bought the pro version, we're already using the latest version and  saw that you used legacy laravel/ui with framework upgrade from 7 to 8. 
Upgrade because Laravel 8 out of the box now comes with Models Directory (app/Models), introduced Dynamic Blade Components and have entirely re-written as Model factories classes. 
Also, most important thing: for UI, Laravel Breeze or Laravel Jetstream are heavily promoted and laravel/ui package's usage is discouraged from use in the future.

Any chance to upgrade the Pro theme to use Laravel Breeze or Laravel Jetstream with both stacks (Livewire + Blade / Inertia + Vue) ?

**Comment by teamupdivision** [comment]
Hi @alinmiron,

Thank you very much for using Creative Tim products and for sharing this. We will definitely take this into account for the next upgrades!

All the best,
Updivision Team
