### ISSUE TITLE
npm run production fails -> 100% - $icon-size-xl - 1

### ISSUE THREAD

**Issue by magarrent** [creativetimofficial/ct-argon-dashboard-pro-laravel#32]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [NO ] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Compile production assets

# Current Behavior

There is an error in the compilation process

## Steps to Reproduce

just run 
`npm run production`

## Context

npm 6.14.8
node v14.15.0

![image](https://user-images.githubusercontent.com/6561770/112389862-b2d34b00-8cf5-11eb-9bac-fbce56aa6e52.png)
![image](https://user-images.githubusercontent.com/6561770/112389920-c8487500-8cf5-11eb-869b-ef977ce2def1.png)

**Comment by magarrent** [comment]
**Solution**

Change

`width: calc(100% - $icon-size-xl} - 1);`

for

`width: calc(100% - #{$icon-size-xl} - 1);`

Just put the variables inside **#{}**

**Comment by teamupdivision** [comment]
Hi @mgarcia96,

Thank you for reporting this issue and for using Creative Tim products.
We've pushed a fix to this problem.

You can access it from the downloads section in the Creative Tim website.

All the best,
Updivision Team
