### ISSUE TITLE
Sidebar Animation

### ISSUE THREAD

**Issue by demon0430** [creativetimofficial/ct-argon-dashboard-pro-laravel#34]
Hi,

I am using the latest version of the argon dashboard template and is trying to recreate this workaround but is having a problem with this instruction:

public/argon/css/argon.css, remove .sidenav:hover { max-width: 250px; }

the new version has the minified version argon.min.css.

Can you help me locate or update the minified version.

Related Ticket: https://github.com/creativetimofficial/ct-argon-dashboard-pro-laravel/issues/22

Thanks

**Comment by teamupdivision** [comment]
Hi @demon0430,

Thanks for sending this and for using Creative Tim products. 

You can overwrite this css in your custom css file (if you don't have one, you can create in public/css and import it in app.blade.php). Import your css file after the argon file and it will have priority.

Please let us know if this helped and if there is anything else we can do.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @demon0430,

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @demon0430,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
