### ISSUE TITLE
Others Theme?

### ISSUE THREAD

**Issue by marcosana2020** [creativetimofficial/ct-argon-dashboard-pro-laravel#35]
Is possible change theme?
there is
Another color palette?

**Comment by teamupdivision** [comment]
Hi @marcosana2020,

Thank you for sending this and for using Creative Tim products.

Unfortunately, the Argon theme doesn't have a color palette, but you may change the colors that you want by changing the bootstrap classes or you may create your own color classes.

Please let us know if there is anything else we can help with.

Best,
Updivision Team

**Comment by marcosana2020** [comment]
Ready!

**Comment by teamupdivision** [comment]
Hi @marcosana2020,

Thank you. If there is anything else we can help with, please feel free to let us know.

Please let us know if you have any other issues. 

All the best,
Updivision Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
