### ISSUE TITLE
Range slider Result

### ISSUE THREAD

**Issue by marcosana2020** [creativetimofficial/ct-argon-dashboard-pro-laravel#36]
argon laravel
In component range-slider-value value-high, how capturing two values ..in input forms?

**Comment by rarestoma** [comment]
Hi @marcosana2020,

Thank you for working with our products.

We provide an example with 2 values for the slider in this page: https://www.creative-tim.com/live/argon-dashboard-pro-laravel.

Can you please tell me if it is good for you? Or give me an example of what would you need?

Thank you,
Rares

**Comment by teamupdivision** [comment]
Hi @marcosana2020,

We will close this ticket for now, but if you encounter any other issues, please let us know.

Best,
UPDIVISION Team
