### ISSUE TITLE
Hi, I just can't figure out how to use full calendar. would you have a simple example with controller on how to view and add events? Thanks

### ISSUE THREAD

**Issue by stefdec** [creativetimofficial/ct-argon-dashboard-pro-laravel#37]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @stefdec,

Thanks for your question and for using Creative Tim products.

Please check out the https://fullcalendar.io/ documentation for more info on how to use the calendar. Let us know if this helped and if you need additional info or details.

Best,
UPDIVISON Team

**Comment by teamupdivision** [comment]
Hi there @stefdec, 

We would like to check if this helped and if there is any other info needed for this.
Please let us know if you have any other issues. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @stefdec,

Hope this helped. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
