### ISSUE TITLE
Horizontal scroll bar at the bottom of the page

### ISSUE THREAD

**Issue by leonardocaitano** [creativetimofficial/ct-argon-dashboard-pro-laravel#39]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Without scroll on bottom page

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

A horizontal scroll appear on bottom page

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Check https://www.creative-tim.com/live/argon-dashboard-pro-laravel
2. Click on Dashboard > alternative
2. A horizontal scroll appear on bottom page

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Chrome
* Operating System: Windows 10
* Browser and Version: Latest

## Failure Logs
![bug](https://user-images.githubusercontent.com/998041/147790101-f36771c1-9442-4eb9-8b9a-8d17d0c54bfc.png)

**Comment by leonardocaitano** [comment]
any ideia?

**Comment by teamupdivision** [comment]
Hi @LeonardoCaitano,

Thanks for reporting this and for using Creative Tim products.

Could you try using for body classes the following: class="w-100" and style="overflow-x: hidden"?

Please let us know if this helped or if you need any additional info.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @LeonardoCaitano, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @LeonardoCaitano,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
