### ISSUE TITLE
Building assets with webpack

### ISSUE THREAD

**Issue by LarryBarker** [creativetimofficial/ct-argon-dashboard-pro-laravel#4]
# Expected Behavior

We recently purchased a developer license for this package and would like to be able to use Laravel Mix to compile our assets. Also, we are looking for more information on how to customize colors.

Ideally, we would update the `package.json` file in our project root, use `npm install` to install dependencies, and compile/build `resources/js/app.js` and `resources/sass/app.scss` with `npm run dev` or `npm run prod`

# Current Behavior

Public assets come pre-build and are bloating the public directory.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows 10 & MacOS Mojave 10.14
* Browser and Version: Chrome

**Comment by LarryBarker** [comment]
It seems like there are missing image files in the resources directory:

```
[data-calendar-month="0"] {
    background-image: url('../img/calendar/january.jpg');
}
[data-calendar-month="1"] {
    background-image: url('../img/calendar/february.jpg');
}
[data-calendar-month="2"] {
    background-image: url('../img/calendar/march.jpg');
}
[data-calendar-month="3"] {
    background-image: url('../img/calendar/april.jpg');
}
[data-calendar-month="4"] {
    background-image: url('../img/calendar/may.jpg');
}
[data-calendar-month="5"] {
    background-image: url('../img/calendar/june.jpg');
}
[data-calendar-month="6"] {
    background-image: url('../img/calendar/july.jpg');
}
[data-calendar-month="7"] {
    background-image: url('../img/calendar/august.jpg');
}
[data-calendar-month="8"] {
    background-image: url('../img/calendar/september.jpg');
}
[data-calendar-month="9"] {
    background-image: url('../img/calendar/october.jpg');
}
[data-calendar-month="10"] {
    background-image: url('../img/calendar/november.jpg');
}
[data-calendar-month="11"] {
    background-image: url('../img/calendar/december.jpg');
}
```

**Comment by Ghitu** [comment]
Hello @LarBearrr, sorry for the delayed reply.
I will follow up with an answer ASAP

**Comment by LarryBarker** [comment]
@Ghitu Thank you, I look forward to your reply!

**Comment by Ghitu** [comment]
Hello @LarBearrr 
At the moment you can only compile the SASS files, check this link to see more info: https://argon-dashboard-pro-laravel.creative-tim.com/docs/getting-started/build-tools.html

The images you are referring are not used, you can remove them from the SASS file.
