### ISSUE TITLE
[Bug] El boton File browser no se visualiza que documento se sube

### ISSUE THREAD

**Issue by Lamb11** [creativetimofficial/ct-argon-dashboard-pro-laravel#42]
### Version
Premium Bootstrap 4 Dashboard built for Laravel
### Reproduction link
https://codepen.io/alberto-cordero-arellanes/pen/gOoVKPv
### Operating System
iOS
### Device
En todos
### Browser & Version
Chrome
### Steps to reproduce
Pongo este codigo html y cuando subo un archivo no se visualiza el archivo que subo
### What is expected?
Espero que cuando se suba el archivo se vea el nombre del archivo
### What is actually happening?
No se ve el nombre del archivo

---

**Comment by teamupdivision** [comment]
Hello @Lamb11,

Thank you for using the Creative Tim products and for informing us of this issue.

For the file name to show in the label box you need to add for the form-group of photo in the label tag the classes class="custom-file-label text-truncate" and at the end of the file after the endsection you need to push a js script with:
@push('js')
    <script>
        $('.custom-file-input').on('change', function() {
            let fileName = $(this).val().split('\').pop();
            $(this).next('.custom-file-label').addClass("selected").html(fileName);
        });
    </script>
@endpush

This will help you see the file name and you can add it both in your create and edit blades.

If you need any other information, please let us know.

Best,
UPDIVISION Team

**Comment by Lamb11** [comment]
Hola buenas noches no sirvio correctamente, al subir mi archivo me marca null, no carga mi archivo si le quito el estilo si lee mi archivo correctamente, si subo mi archivo con el nombre ejemplo.01 solo se ve una letra, y ademas no se sube mi archivo bueno más bien no lo lee. Además quiero que diga Buscar aparece Browse

` <form action="{{route('report.importExtendedStorageData', $account) }}" method="post" enctype="multipart/form-data">
                                        @csrf
                                        <input type="file" class="custom-file-input" id="customFileLang" lang="es"/>
                                        <label class="custom-file-label text-truncate"  for="customFileLang"></label>
                                        <br><br>
                                        <button type="submit" class="btn btn-primary btn-round">Importar Almacenamiento Prolongado</button>
                                        <span class="float-right mr-4"><a href="{{ route('report.getLongStorageData', ['account' => $account]) }}" target="_blank" id="cmd" class="btn btn-sm btn-primary">{{ __('Descargar') }}</a></span>
                                    </form>`

y hasta abajo tengo `@Push('js')
<script>
$('.custom-file-input').on('change', function() {
let fileName = $(this).val().split('').pop();
$(this).next('.custom-file-label').addClass("selected").html(fileName);
});
</script>
@endpush`

**Comment by teamupdivision** [comment]
Hi @Lamb11,

Please check the class of input to be custom-file-input, with no spaces, and to match with the one in the js script. Make sure that @push is not with first letter uppercase and check your routes and actions. If you want, you can share the controllers and blades with us. 

For overwriting the default name of the button, you should add at the end of the <head> tag from app.blade.php this:
        <style>
            .custom-file-input:lang(en)~.custom-file-label::after {
                content: "Search";
            }
        </style>
        
Please let us know if this worked.

Best, 
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @Lamb11,

We hope that our instructions helped you with that issue.

Should you have any other questions or problems, please do not hesitate to contact us.

Best,
UPDIVISION Team
