### ISSUE TITLE
css and js not loading

### ISSUE THREAD

**Issue by travissaron** [creativetimofficial/ct-argon-dashboard-pro-laravel#44]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Login screen to be displayed correctly

# Current Behavior

Login screen is being displayed without js (it is trying to load them from document root rather than the project directory)

![Screen Shot 2022-12-25 at 2 15 20 pm](https://user-images.githubusercontent.com/29095547/209458748-a9633b79-d8cf-4332-add8-77037e98e165.png)

**Comment by teamupdivision** [comment]
Hello, 
Thank you for using CT products!
Can you please send us you .env file and the steps you made during the installation?
Thank you

**Comment by travissaron** [comment]
.env

APP_NAME=VRA
APP_ENV=local
APP_KEY=base64:PtWJdjXLhQmjffSuxABpj7IpLwVhzuK+/k9eZRAIJhs=
APP_DEBUG=true
APP_URL=http://localhost:8888/vra

IS_DEMO=

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=8889
DB_DATABASE=vra-dev
DB_USERNAME=vradev
DB_PASSWORD=vradev

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by travissaron** [comment]
This is a MAMP environment.

Install steps (as per the readme.md):
1. Unzip the downloaded archive
2. Copy and paste **argon-dashboard-pro-laravel-master** folder in your **projects** folder. Rename the folder to your project's name
3. In your terminal run `composer install`
4. Copy `.env.example` to `.env` and updated the configurations (mainly the database configuration: database name, user name and password, set the APP_URL to the right path)
5. In your terminal run `php artisan key:generate`
6. Run `php artisan migrate --seed` to create the database tables and seed the roles and users tables
7. Run `php artisan storage:link`

**Comment by travissaron** [comment]
Resovled. Added a virtual host using MAMP Pro and all seems to work properly. Thanks.
