### ISSUE TITLE
Update to latest laravel [premium support]

### ISSUE THREAD

**Issue by heshamwatany** [creativetimofficial/ct-argon-dashboard-pro-laravel#46]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
To be easier to sync with latest laravel

# Current Behavior

When I downloaded the theme after purchase, I find it on laravel 9 not 10

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Download the code after purchase
2. You will find it is already implemented in laravel 9
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: pc
* Operating System: windows
* Browser and Version: latest chrome

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products.

 Could you please send us the .env file and the composer.json?

Also could you please let us know what version of Argon PRO Laravel you have?

**Comment by heshamwatany** [comment]
it is laravel 10 sorry
