### ISSUE TITLE
Upload Profile Photo Field UI can be improved.

### ISSUE THREAD

**Issue by ziming** [creativetimofficial/ct-argon-dashboard-pro-laravel#6]
On edit profile page, choosing an image does not change the file input to show the file name. Making people mistook it as a file is not chosen when it has.

Go https://argon-dashboard-pro-laravel.creative-tim.com/profile and choose a profile photo and you will get what I mean.

Thank you

**Comment by Ghitu** [comment]
Hello @ziming, here is a temporary solution to append the code with:
https://stackoverflow.com/questions/43250263/bootstrap-4-file-input

We'll make this change in one of our future releases also.

Thank you very much for your feedback!
