### ISSUE TITLE
Forms Validation Page

### ISSUE THREAD

**Issue by adeluna84** [creativetimofficial/ct-argon-dashboard-pro-laravel#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

ErrorException (E_ERROR)
htmlspecialchars() expects parameter 1 to be string, array given (View: C:\xampp\htdocs\BeBee\resources\views\pages\validation.blade.php)
Previous exceptions
htmlspecialchars() expects parameter 1 to be string, array given (0)

C:\xampp\htdocs\BeBee\vendor\laravel\framework\src\Illuminate\Support\helpers.php
 
        return $target;
    }
}
 
if (! function_exists('e')) {
    /**
     * Encode HTML special characters in a string.
     *
     * @param  \Illuminate\Contracts\Support\Htmlable|string  $value
     * @param  bool  $doubleEncode
     * @return string
     */
    function e($value, $doubleEncode = true)
    {
        if ($value instanceof Htmlable) {
            return $value->toHtml();
        }
 
        return htmlspecialchars($value, ENT_QUOTES, 'UTF-8', $doubleEncode);
    }
}
 
if (! function_exists('ends_with')) {
    /**
     * Determine if a given string ends with a given substring.
     *
     * @param  string  $haystack
     * @param  string|array  $needles
     * @return bool
     *
     * @deprecated Str::endsWith() should be used directly instead. Will be removed in Laravel 5.9.
     */
    function ends_with($haystack, $needles)
    {
        return Str::endsWith($haystack, $needles);
    }
}
 
if (! function_exists('env')) {
Arguments
"htmlspecialchars() expects parameter 1 to be string, array given (View: C:\xampp\htdocs\BeBee\resources\views\pages\validation.blade.php)"

# Current Behavior

Im trying to acces to Forms // Validations Page and shows that error

**Comment by Ghitu** [comment]
Hello, thanks for using our products!
The problem with mac/windows computers is that they're key insensitive. And this code `__('Validation')` will generate an error because the validation.php language file returns an array, while the method __() expects a string as parameter.
If you delete this line of code from the file, it will load the page:
`__('Validation')`

**Comment by adeluna84** [comment]
Thanks!!!! :) it works
