### ISSUE TITLE
Verify email blade file need an update for Laravel 6

### ISSUE THREAD

**Issue by ziming** [creativetimofficial/ct-argon-dashboard-pro-laravel#9]
In Laravel 6 upgrade guide it says this:

https://laravel.com/docs/6.0/upgrade#email-verification-route

> To prevent possible CSRF attacks, the email/resend route registered by the router when using Laravel's built-in email verification has been updated from a GET route to a POST route. Therefore, you will need to update your frontend to send the proper request type to this route...

**Comment by eugentudorache** [comment]
Hello @ziming 
The presets are currently compatible with Laravel version 5.8.
We'll do the compatibility update to Laravel version 6 in the next weeks.

Best
Eugen
